### ISSUE TITLE
Uncaught SyntaxError: The requested module 'lodash' does not provide an export named 'debounce'

### ISSUE THREAD

**Issue by Jessicasciani** [stimulus-components/stimulus-auto-submit#2]
Hello
I'm trying to follow the official doc to use stimulus-rails-autosave, but it's throwing me this error

Uncaught SyntaxError: The requested module 'lodash' does not provide an export named 'debounce'

I could not solve it and don't understand where it comes from. I've pinned lodash to my importmap.rb too but still same error

Thanks a lot!

**Comment by guillaumebriday** [comment]
Hello,

How did you import the package exactly?

**Comment by Jessicasciani** [comment]
Hello,

As I'm on Rails 7 I did:

./bin/importmap pin @rails/ujs
./bin/importmap pin stimulus-rails-autosave

I tried with yarn though just in case but it did not work either

**Comment by thomassarafian** [comment]
**SOLUTION :** 
**Step 1 - Install autosave and debounce (from lodash)**

- Run 3 commands in your terminal :
`./bin/importmap pin @rails/ujs`
`./bin/importmap pin stimulus-rails-autosave`
` ./bin/importmap pin lodash.debounce`

**Step 2 - Create a file called `app/javascript/controllers/autosave.js` and copy this file https://pastebin.com/JT0SXiGD**

**Step 3 - In `app/javascript/controllers/application.js` put this :** 

```
import { Application } from '@hotwired/stimulus'
import Rails from '@rails/ujs'
import Autosave from './admin/autosave'

const application = Application.start()

application.debug = false
window.Stimulus   = application

application.register('autosave', Autosave)

export { application }
```

**Comment by guillaumebriday** [comment]
Fixed in https://github.com/stimulus-components/stimulus-auto-submit/commit/8927490102507d69e92d771d7760b6e2094a674b

Thanks for reporting!
